[tool.poetry]
name = "item database"
version = "0.1.0"
description = "We are making a database"
authors = ["James Su"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
